export type RuleFacts = {
  moves: Set<string>; moveTargets: Set<string>; abilities: Set<string>; items: Set<string>; statuses: Set<string>;
  effects: string; entityDescriptions: string; closed: boolean; mega: boolean;
};
export type ReviewedRule = { id: string; sources: string[]; text: string; applies?: (facts: RuleFacts) => boolean };
const hasMove = (facts: RuleFacts, ...ids: string[]) => ids.some(id => facts.moves.has(id));
const hasEffect = (facts: RuleFacts, ...names: string[]) => names.some(name => facts.effects.includes(name));
const statusPossible = (facts: RuleFacts, code: string, words: RegExp) =>
  facts.statuses.has(code) || words.test(facts.entityDescriptions);
export const reviewedRules: ReviewedRule[] = [
  { id: 'decision-contract', sources: ['C01','C02','C21'], text: 'Select one supplied complete joint option to improve the chance of winning the whole battle. Options are legal to submit, not guaranteed to hit or succeed. Opponent commands and future random results remain unknown. Rules describe conditional effects, not observed facts. Each Pokemon retains its own PP, status and counters. A replacement does not inherit the departing Pokemon’s unexecuted attack.' },
  { id: 'action-order', sources: ['C03'], text: 'Ordinary voluntary switches precede Mega Evolution, which precedes ordinary moves. Entry effects can change the field first. Higher move priority acts before lower priority; within a bracket effective Speed normally decides, with random speed ties. Speed changes, including weather, Mega and Tailwind, can reorder remaining actions immediately, never grant an already-acting Pokemon another ordinary action. Trick Room reverses Speed within each bracket, not priority; Champions has no extreme-Speed wraparound. Acting early within a bracket is not positive priority.' },
  { id: 'execution', sources: ['C04','C07'], text: 'An action can be interrupted before the move starts; ordinary PP deduction follows the ability-to-move checks. Executed moves normally spend PP even on a miss or failure. Reachability, protection, move/type immunities, accuracy and move-specific conditions still apply; even a 100% secondary needs its trigger. Events between actions can consume items, change stats, cause KOs or switches. Category, contact, spread targeting, multiple hits and self effects are distinct. The protect flag means blockable by protection, not that the move protects its user; bypasssub concerns Substitute, not Protect. Accuracy true means no ordinary accuracy check, not guaranteed success.' },
  { id: 'targets', sources: ['C05'], text: 'Use the supplied explicit targets. All active positions in doubles are adjacent. A target is ordinarily a position: a switch-in can receive the attack aimed there. An ordinary single-target attack whose opposing target faints can retarget an eligible remaining foe; an attack aimed at a fainted ally can fail instead. No remaining foes does not automatically retarget the partner. Redirection and special target-selection rules apply separately.' },
  { id: 'spread', sources: ['C06'], applies: f => f.moveTargets.has('allAdjacent') || f.moveTargets.has('allAdjacentFoes'), text: 'allAdjacent can hit the partner; allAdjacentFoes ordinarily cannot. Ordinary spread damage uses 0.75 when the engine initially identifies multiple targets, before each target’s Protect/immunity check. One protected or immune target does not necessarily restore full damage to the other. Targets have separate hit/effect outcomes; Wide Guard tests target category even if only one target remains.' },
  { id: 'type-and-status-immunities', sources: ['C08','C09','C16'], text: 'The ordinary type factors are multiplied across current defensive types, including current Mega types; one immunity makes the ordinary product zero unless an explicit exception bypasses it. Status moves need separate checks. Fire blocks new burn; Electric new paralysis; Ice new freeze; Poison/Steel new poison unless an applicable exception such as Corrosion. Grass blocks powder and initial Leech Seed; opposing Dark blocks a status move actually boosted by Prankster, not own-side/field effects or ally targeting. Ghost bypasses ordinary trapping, not every move lock. Acquiring an immune type does not itself cure existing status. Grounding can change: Gravity/Ingrain/Smack Down/effective Iron Ball can ground; otherwise Flying, applicable levitation, Magnet Rise/Telekinesis/Air Balloon can prevent it. Semi-invulnerability is distinct and move-specific.' },
  { id: 'statistics', sources: ['C10','C11'], text: 'Use supplied actual trained statistics, not species base stats or other-game EV assumptions. Ordinary stat stages cap at -6/+6; stage s uses (2+s)/2 if nonnegative, else 2/(2-s), with engine integer handling. Never apply an already-included modifier twice. Accuracy/evasion instead use combined stage accuracy minus evasion, clamped -6/+6: (3+s)/3 or 3/(3-s). Numeric 100 accuracy can still miss under modifiers; bypassing accuracy does not bypass immunity, protection or semi-invulnerability. Ability/item exceptions and unusual stat substitutions use their own definitions.' },
  { id: 'damage', sources: ['C12','C13','C14'], text: 'Ordinary damage depends on level, effective power, actual offense/defense and ordered integer/fixed-point modifiers; raw power is not HP loss. Normal STAB is 1.5 once for a matching current type; abilities can change it. Ordinary random damage factor ranges 85–100 inclusive. Fixed damage, recoil, HP costs and special stat substitutions follow move definitions. Normal crit chances by additional stage: 1/24,1/8,1/2,1. Crit damage normally multiplies 1.5, ignores negative offensive and positive defensive stages for that hit, and bypasses screens; favorable offense/unfavorable defense still count. Crit does not generally bypass Protect, Substitute, immunity, abilities or burn’s damage penalty. Contact, damage, stat loss, HP thresholds and KO are different triggers. Secondary effects need their conditions; KO/Substitute/abilities may prevent them. Multiple hits can trigger effects between hits; a Sash or Substitute need not stop later hits.' },
  { id: 'status-and-history', sources: ['C15'], text: 'Normally only one major status can exist; applying another does not replace it unless explicitly stated. Volatiles, side and field conditions are separate. Major status normally persists through switching; many volatiles do not. Counters may count checks, successful uses, hits or end-of-turn events, not elapsed turns. Bench time need not advance sleep/freeze. Preserve unknown remaining durations instead of inventing exact countdowns.' },
  { id: 'switches', sources: ['C17'], text: 'A voluntary switch is not an attack by the incoming Pokemon. It ordinarily clears stages and most volatiles, preserving HP/PP/major status; field/side effects remain. Entry abilities/hazards execute in their actual order and can KO the entrant. Pivot moves require their own successful conditions; missing, protection, immunity, KO or competing effects can prevent a pivot. Forced switching and Baton Pass have separate rules. Only selected eligible live reserves can enter; both positions cannot take the same reserve.' },
  { id: 'mega', sources: ['C18'], applies: f => f.mega, text: 'One Mega Evolution per side per battle, even with several stones. A compatible held stone permits but does not prove transformation. A supplied legal Mega declaration transforms before ordinary moves, using the new types, trained stats and current ability; ability effects and new Speed can matter immediately. It is not an extra attack. The form persists after switching and fainting; the stone is not consumed. Form after Revival Blessing is uncertain. Do not introduce unsupported transformation mechanics.' },
  { id: 'ability-and-item-state', sources: ['C19','M26','M27'], text: 'Apply the holder’s current effective ability and item, with their exact triggers. Suppressed, bypassed for one hit, replaced, removed and consumed are distinct states. A consumed item does not reappear on switching. Automatic item use can happen during another action or between hits; threshold timing follows its definition. Starting and Mega abilities can differ. Per-entity descriptions below contain the applicable effect and exceptions; family examples do not supply hypothetical abilities/items.' },
  { id: 'fainting-and-residuals', sources: ['C20','M30'], text: 'Fainted Pokemon cannot perform pending ordinary actions; their ability influence can disappear. Replacement timing and battle completion follow the engine, not a net-HP estimate. End-of-turn effects execute sequentially: weather processing(1), future attacks(3), Wish(4), selected passive effects(5: Grassy recovery sub2, Healer sub3, Leftovers sub4), Aqua Ring/Ingrain(6–7), Leech Seed(8), poison(9), burn(10), Nightmare/Curse(11–12), binding/Salt Cure/Octolock(13–14), Taunt/Encore/Disable(15–17), Yawn(23), Perish Song(24), side-condition duration including screens/Tailwind(26), field duration including terrain/rooms(27), selected late ability/item events(28+). These numbers are event ordering, not turn counts or move priority. Effects have suborders and can expire or KO a holder before later recovery. Exact unresolved timing remains unknown.' },
  { id: 'burn', sources: ['M01'], applies: f => statusPossible(f,'brn',/burn/i), text: 'Burn normally deals 1/16 max HP at its residual event with integer handling, unaffected by Protect, and halves physical damage (not displayed Attack). Crit does not remove the penalty. Guts and Facade have exceptions. Magic Guard prevents ordinary chip without curing burn/other effects. Fire typing and relevant ability/terrain/status/Substitute checks can prevent new burn.' },
  { id: 'poison', sources: ['M02'], applies: f => statusPossible(f,'psn',/poison/i) || f.statuses.has('tox'), text: 'Poison normally deals 1/8 max HP. Bad poison uses 1/16 × counter, rising each active poison event up to15; floor the base fraction before multiplying. Switching preserves bad poison but resets escalation. Poison/Steel prevent new poison unless an applicable exception; an existing major status normally blocks application. Poison Heal changes the event to1/8 recovery; Magic Guard can prevent chip without curing status.' },
  { id: 'paralysis', sources: ['M03'], applies: f => statusPossible(f,'par',/paraly/i), text: 'Champions paralysis halves Speed after other applicable modifiers with integer truncation. Quick Feet prevents this halving but not the reached before-move failure check: 1/8 (12.5%) cannot move. An earlier prevention event can avoid reaching that check. Electric blocks new paralysis; Ground immunity to an Electric move is additional, not immunity to every paralysis source. Switching does not cure it.' },
  { id: 'sleep', sources: ['M04'], applies: f => statusPossible(f,'slp',/sleep|asleep|yawn/i), text: 'Champions ordinary sleep starts hidden counter2 with p1/3 or3 with p2/3. Each reached sleep check decrements before wake: first prevents an ordinary move, second wakes the1/3 branch, third wakes the remainder; waking permits the chosen move. Sleep inflicted before action can reach its first check that turn. Bench time does not advance it and switching does not reset it. Early Bird adds a decrement. Only explicitly sleep-usable moves may execute asleep. Rest sets counter3 after healing, normally blocking next2 attempts. Ability/grounded terrain prevention follows its own timing; Electric Terrain does not wake an already sleeping Pokemon.' },
  { id: 'freeze', sources: ['M05'], applies: f => statusPossible(f,'frz',/freez|frozen/i), text: 'Champions freeze starts counter3. A reached check decrements it: zero thaws; otherwise thaw chance is1/4. Thaw permits acting; the third check guarantees thaw without modifiers. Bench time does not check. A user-thaw move or qualifying damaging hit can thaw through its own rules; an immune target may not receive that cure. Ice blocks new freeze; effective sun prevents new freeze but does not blanket-cure existing freeze. Champions Freeze-Dry has no freeze secondary.' },
  { id: 'confusion-and-flinch', sources: ['M06'], applies: f => /confus|flinch/i.test(f.entityDescriptions) || hasEffect(f,'confusion','flinch'), text: 'Ordinary confusion starts uniform counter2–5; decrement each reached check, ending at0 before rolling. While still confused self-hit chance33/100 prevents the selected move; uses own Attack/Defense stages and40-power physical-like damage variation, without ordinary STAB/type/crit/screens/burn penalty. Some sources have other counters. Switching normally removes it. Flinch prevents a not-yet-completed action that turn, never retroactively or ordinarily next turn. Inner Focus prevents flinch; Shield Dust can block a secondary flinch without blocking the move’s damage.' },
  { id: 'personal-protection', sources: ['M09'], applies: f => hasMove(f,'protect','detect','feint','wideguard','quickguard','spikyshield','kingsshield','banefulbunker','silktrap','burningbulwark','endure') || hasEffect(f,'protect'), text: 'Protect/Detect ordinarily priority+4, protect only the user for the turn against eligible other-Pokemon moves, not established residual damage. Shared consecutive-protection success:1,1/3,1/9,… with pinned denominator capped729; failure, adequate break or broken protection resets according to the move. Changing related protection move does not necessarily reset the chain. A protection move can fail if no eligible later action remains. Use individual current/max PP. Variant scope/retaliation differs. Feint can remove protection for later actions; bypassing one hit is not the same as removing it.' },
  { id: 'side-guards', sources: ['M10'], applies: f => hasMove(f,'wideguard','quickguard') || hasEffect(f,'wideguard','quickguard'), text: 'Wide Guard priority+3 protects its side against eligible allAdjacent/allAdjacentFoes category moves, including an ally’s move and when only one target remains. It does not generally block single-target attacks. Quick Guard+3 blocks eligible positive-priority moves, including ability-granted priority or an ally’s move; Speed alone is not priority. Neither guard rolls ordinary consecutive-use failure in Champions, but both can update the shared counter affecting later Protect. Other failure, duplicate protection, timing and bypass rules remain.' },
  { id: 'screens', sources: ['M11'], applies: f => hasMove(f,'reflect','lightscreen','auroraveil') || hasEffect(f,'reflect','lightscreen','auroraveil'), text: 'Reflect reduces eligible physical damage; Light Screen special; doubles multiplier2732/4096 even with only one active ally. Aurora Veil covers both, requires effective snow at setup but not afterward, and does not stack again with a matching screen. Duration normally5 turns including setup,8 with effective Light Clay. Crit and applicable Infiltrator bypass. Brick Break/Psychic Fangs remove before damage; Defog has its own removal. Residual/fixed damage/HP costs are not automatically reduced.' },
  { id: 'weather', sources: ['M15'], applies: f => /weather|rain|sun|snow|sandstorm/i.test(f.entityDescriptions) || hasEffect(f,'weather'), text: 'Only one ordinary weather; a different setter replaces it. Normally5 turns including creation,8 with the matching effective rock, including ability-set weather. Rain multiplies Water damage1.5 and Fire0.5; sun Fire1.5 and Water0.5, preventing new freeze. Hurricane/Thunder bypass ordinary accuracy in rain and ordinarily50% in sun. Weather Ball changes type/power through its own conditions. Solar moves can skip charge in sun. Matching active weather-Speed abilities double Speed, not priority; do not infer an ability from species. Cloud Nine/Air Lock suppress effects, not necessarily stored weather/duration. Competing switch-in and Mega setters resolve in actual action order, potentially changing later moves.' },
  { id: 'sand-and-snow', sources: ['M15'], applies: f => f.abilities.has('snowwarning') || f.abilities.has('sandstream') || /sandstorm|\bsnow\b|snowscape|slush rush|sand rush/i.test(f.entityDescriptions) || hasEffect(f,'sandstorm','snow','hail'), text: 'Sandstorm boosts Rock Special Defense1.5 and deals susceptible holders1/16 max-HP chip; Rock/Ground/Steel are immune to that chip. Snow boosts Ice Defense1.5 and has no hail chip. Neither simply boosts all attacks of its own type. Blizzard bypasses ordinary accuracy in snow. Applicable weather-Speed abilities have their exact conditions.' },
  { id: 'tailwind', sources: ['M21'], applies: f => hasMove(f,'tailwind') || hasEffect(f,'tailwind'), text: 'Tailwind doubles Speed on its side for4 turns including setup. It persists after the setter switches/faints and can reorder actions still pending this turn. Under Trick Room higher Speed can instead move later within a priority bracket.' },
  { id: 'choice-and-first-action', sources: ['M23'], applies: f => f.items.has('choicescarf') || hasMove(f,'fakeout','firstimpression','struggle') || /charg|two.turn|following turn/i.test(f.entityDescriptions) || hasEffect(f,'recharge','twoturnmove','choicelock'), text: 'Effective Choice Scarf multiplies Speed1.5 and normally locks into the first executed move; switching clears lock, and item changes/suppression matter. Multi-turn charging, locked continuation and recharge follow the exact move/request, not a fresh unrestricted action. Fake Out and First Impression require the qualifying first move opportunity after entry; Champions disables them afterward even when an earlier opportunity was prevented by status. Switching out/back resets entry eligibility. Fake Out+3 includes flinch; First Impression+2 has power100. Forced Struggle is available only as supplied, with typeless damage, engine target and quarter-max-HP recoil.' },
  { id: 'dire-claw-statuses', sources: ['M29','move:direclaw'], applies: f => hasMove(f,'direclaw'), text: 'Champions Dire Claw has30% chance to attempt one randomly selected status among poison, paralysis and sleep. It does not reroll until a status succeeds. Include all three status rules and immunity checks. It carries the slicing flag.' },
];
export const optionalReminders = [
  { id:'interaction:weather-speed', title:'Weather and remaining move order', text:'Weather-dependent Speed requires the actual effective ability and weather. Recompute remaining order after a weather or Mega change; Speed never changes a move’s priority.', rule:'weather' },
  { id:'interaction:mega-form-state', title:'Available Mega versus current form', text:'A stone permits a transformation; only an actual declaration/current form establishes its ability and statistics. Several stones still share one Mega use per side.', rule:'mega' },
  { id:'interaction:guards-and-target-shape', title:'Guard scope', text:'Guard eligibility comes from target category or positive priority, not the number of targets currently present. Bypass and removal remain different effects.', rule:'side-guards' },
  { id:'interaction:dark-prankster', title:'Prankster and the recipient', text:'Prankster immunity belongs to an opposing Dark recipient of a boosted move; own-side screens, field effects and ally targeting do not acquire that immunity check.', rule:'type-and-status-immunities' },
] as const;
